Image = "https://static.datasektionen.se/splash-lite.jpg"
Title = "Konglig Datasektionen"
Message = "Är du nyantagen till civilingenjörsprogrammet i Datateknik på KTH i höst? Då har du hittat rätt. Välkommen till Konglig Datasektionen! För information, schema och kontaktuppgifter till Mottagningen, klicka här."